@startuml iof
' !include C:\Users\arkop\git\IOF-Visual\ontopuml-dev\ontologyv2.iuml
!include ontologyv2.iuml

skinparam class{
 fontColor white
}
skinparam object{
    BackgroundColor 76608A
    fontColor White
    BorderColor White 
    FontName Helvetica   
}

!$namespace_colors = { "bfo" : "DFA702", 
                        "iof":"1E90FF", 
                        "ns":"Green", 
                        "ns1":"76608A"}
!$namespace_default_color = "DarkGrey"
@enduml