PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mt: <https://purl.mtconnect.org/ontology/construct/>
PREFIX ex: <http://example.com/data/>


SELECT *
WHERE 
{
  ?d mt:hasCapability ?c .
  ?c rdf:type?e .
  FILTER (?e != owl:Thing && ?e != mt:Capability)
}

