
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title MazakFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "data":"76608A",
                      "mt":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, mt:ontology1, owl:Ontology)
individual(o2, data:Mazak317641d1, mt:[[../MTConnect.html#Device Device]])
individual(o3, data:Mazak317641d1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o4, data:Mazak317641d1AVAILABILITY, mt:[[../MTConnect.html#AvailabilityDataItem AvailabilityDataItem]])
individual(o5, data:Mazak317641d1ASSET_CHANGED, mt:[[../MTConnect.html#AssetChangedDataItem AssetChangedDataItem]])
individual(o6, data:Mazak317641d1ASSET_REMOVED, mt:[[../MTConnect.html#AssetRemovedDataItem AssetRemovedDataItem]])
individual(o7, data:Mazak317641d1a, mt:[[../MTConnect.html#Axes Axes]])
individual(o8, data:Mazak317641d1aCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o9, data:Mazak317641d1aSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o10, data:Mazak317641d1ax, mt:[[../MTConnect.html#Linear Linear]])
individual(o11, data:Mazak317641d1axCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o12, data:Mazak317641d1axPOSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o13, data:Mazak317641d1axPOSITION_CONDITION, mt:[[../MTConnect.html#PositionConditionDataItem PositionConditionDataItem]])
individual(o14, data:Mazak317641d1axTEMPERATURE, mt:[[../MTConnect.html#TemperatureDataItem TemperatureDataItem]])
individual(o15, data:Mazak317641d1ay, mt:[[../MTConnect.html#Linear Linear]])
individual(o16, data:Mazak317641d1ayCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o17, data:Mazak317641d1ayPOSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o18, data:Mazak317641d1ayPOSITION_CONDITION, mt:[[../MTConnect.html#PositionConditionDataItem PositionConditionDataItem]])
individual(o19, data:Mazak317641d1ayTEMPERATURE, mt:[[../MTConnect.html#TemperatureDataItem TemperatureDataItem]])
individual(o20, data:Mazak317641d1az, mt:[[../MTConnect.html#Linear Linear]])
individual(o21, data:Mazak317641d1azCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o22, data:Mazak317641d1azPOSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o23, data:Mazak317641d1azPOSITION_CONDITION, mt:[[../MTConnect.html#PositionConditionDataItem PositionConditionDataItem]])
individual(o24, data:Mazak317641d1azTEMPERATURE, mt:[[../MTConnect.html#TemperatureDataItem TemperatureDataItem]])
individual(o25, data:Mazak317641d1ac, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o26, data:Mazak317641d1acCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o27, data:Mazak317641d1acROTARY_VELOCITY:ACTUAL, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o28, data:Mazak317641d1acTEMPERATURE, mt:[[../MTConnect.html#TemperatureDataItem TemperatureDataItem]])
individual(o29, data:Mazak317641d1acTEMPERATURE_CONDITION, mt:[[../MTConnect.html#TemperatureConditionDataItem TemperatureConditionDataItem]])
individual(o30, data:Mazak317641d1abr, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o31, data:Mazak317641d1abrCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o32, data:Mazak317641d1abrANGLE_CONDITION, mt:[[../MTConnect.html#AngleDataItem AngleDataItem]])
individual(o33, data:Mazak317641d1abrANGLE:ACTUAL, mt:[[../MTConnect.html#AngleActualDataItem AngleActualDataItem]])
individual(o34, data:Mazak317641d1ac2, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o35, data:Mazak317641d1ac2Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o36, data:Mazak317641d1ac2ANGLE_CONDITION, mt:[[../MTConnect.html#AngleDataItem AngleDataItem]])
individual(o37, data:Mazak317641d1ac2ANGLE:ACTUAL, mt:[[../MTConnect.html#AngleActualDataItem AngleActualDataItem]])
individual(o38, data:Mazak317641d1ac2TEMPERATURE_CONDITION, mt:[[../MTConnect.html#TemperatureConditionDataItem TemperatureConditionDataItem]])
individual(o39, data:Mazak317641d1cont, mt:[[../MTConnect.html#Controller Controller]])
individual(o40, data:Mazak317641d1contCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o41, data:Mazak317641d1contSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o42, data:Mazak317641d1contpath1, mt:[[../MTConnect.html#Path Path]])
individual(o43, data:Mazak317641d1contpath1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o44, data:Mazak317641d1contpath1PATH_POSITION, mt:[[../MTConnect.html#PathPositionDataItem PathPositionDataItem]])
individual(o45, data:Mazak317641d1contpath1PATH_FEEDRATE_OVERRIDE:RAPID, mt:[[../MTConnect.html#PathFeedrateOverrideRapidDataItem PathFeedrateOverrideRapidDataItem]])
individual(o46, data:Mazak317641d1contpath1PATH_FEEDRATE_OVERRIDE:PROGRAMMED, mt:[[../MTConnect.html#PathFeedrateOverrideProgrammedDataItem PathFeedrateOverrideProgrammedDataItem]])
individual(o47, data:Mazak317641d1contpath1PATH_FEEDRATE:ACTUAL, mt:[[../MTConnect.html#PathFeedrateActualDataItem PathFeedrateActualDataItem]])
individual(o48, data:Mazak317641d1contpath1EXECUTION, mt:[[../MTConnect.html#ExecutionDataItem ExecutionDataItem]])
individual(o49, data:Mazak317641d1contpath1CONTROLLER_MODE, mt:[[../MTConnect.html#ControllerModeDataItem ControllerModeDataItem]])
individual(o50, data:Mazak317641d1contpath1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o51, data:Mazak317641d1systems, mt:[[../MTConnect.html#Systems Systems]])
individual(o52, data:Mazak317641d1systemsCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o53, data:Mazak317641d1systemshydraulic, mt:[[../MTConnect.html#Hydraulic Hydraulic]])
individual(o54, data:Mazak317641d1systemshydraulicCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o55, data:Mazak317641d1systemshydraulicSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o56, data:Mazak317641d1systemscoolant, mt:[[../MTConnect.html#Coolant Coolant]])
individual(o57, data:Mazak317641d1systemscoolantCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o58, data:Mazak317641d1systemscoolantSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o59, data:Mazak317641d1systemscoolantTEMPERATURE, mt:[[../MTConnect.html#TemperatureDataItem TemperatureDataItem]])
individual(o60, data:Mazak317641d1systemspneumatic, mt:[[../MTConnect.html#Pneumatic Pneumatic]])
individual(o61, data:Mazak317641d1systemspneumaticCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o62, data:Mazak317641d1systemspneumaticSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o63, data:Mazak317641d1systemslubrication, mt:[[../MTConnect.html#Lubrication Lubrication]])
individual(o64, data:Mazak317641d1systemslubricationCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o65, data:Mazak317641d1systemslubricationSYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o66, data:Mazak317641d1resourcesm, mt:[[../MTConnect.html#Resources Resources]])
individual(o67, data:Mazak317641d1resourcesmCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o68, data:Mazak317641d1resourcesmpersonnelm, mt:[[../MTConnect.html#Personnel Personnel]])
individual(o69, data:Mazak317641d1resourcesmpersonnelmCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o70, data:Mazak317641d1resourcesmpersonnelmUSER, mt:[[../MTConnect.html#UserDataItem UserDataItem]])
individual(o71, data:Mazak317641d1resourcesmmaterials, mt:[[../MTConnect.html#Materials Materials]])
individual(o72, data:Mazak317641d1resourcesmmaterialsCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o73, data:Mazak317641d1resourcesmmaterialsprocstock, mt:[[../MTConnect.html#Stock Stock]])
individual(o74, data:Mazak317641d1resourcesmmaterialsprocstockCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o75, data:Mazak317641d1resourcesmmaterialsprocstockMATERIAL, mt:[[../MTConnect.html#MaterialDataItem MaterialDataItem]])
property(o0, "owl:imports", o1)
property(o2, "mt:hasCapability", o3)
property(o2, "mt:observes", o4)
property(o2, "mt:observes", o5)
property(o2, "mt:observes", o6)
property(o2, "mt:hasComponent", o7)
property(o7, "mt:hasCapability", o8)
property(o7, "mt:observes", o9)
property(o7, "mt:hasComponent", o10)
property(o10, "mt:hasCapability", o11)
property(o10, "mt:observes", o12)
property(o10, "mt:observes", o13)
property(o10, "mt:observes", o14)
property(o7, "mt:hasComponent", o15)
property(o15, "mt:hasCapability", o16)
property(o15, "mt:observes", o17)
property(o15, "mt:observes", o18)
property(o15, "mt:observes", o19)
property(o7, "mt:hasComponent", o20)
property(o20, "mt:hasCapability", o21)
property(o20, "mt:observes", o22)
property(o20, "mt:observes", o23)
property(o20, "mt:observes", o24)
property(o7, "mt:hasComponent", o25)
property(o25, "mt:hasCapability", o26)
property(o25, "mt:observes", o27)
property(o25, "mt:observes", o28)
property(o25, "mt:observes", o29)
property(o7, "mt:hasComponent", o30)
property(o30, "mt:hasCapability", o31)
property(o30, "mt:observes", o32)
property(o30, "mt:observes", o33)
property(o7, "mt:hasComponent", o34)
property(o34, "mt:hasCapability", o35)
property(o34, "mt:observes", o36)
property(o34, "mt:observes", o37)
property(o34, "mt:observes", o38)
property(o2, "mt:hasComponent", o39)
property(o39, "mt:hasCapability", o40)
property(o39, "mt:observes", o41)
property(o39, "mt:hasComponent", o42)
property(o42, "mt:hasCapability", o43)
property(o42, "mt:observes", o44)
property(o42, "mt:observes", o45)
property(o42, "mt:observes", o46)
property(o42, "mt:observes", o47)
property(o42, "mt:observes", o48)
property(o42, "mt:observes", o49)
property(o42, "mt:observes", o50)
property(o2, "mt:hasComponent", o51)
property(o51, "mt:hasCapability", o52)
property(o51, "mt:hasComponent", o53)
property(o53, "mt:hasCapability", o54)
property(o53, "mt:observes", o55)
property(o51, "mt:hasComponent", o56)
property(o56, "mt:hasCapability", o57)
property(o56, "mt:observes", o58)
property(o56, "mt:observes", o59)
property(o51, "mt:hasComponent", o60)
property(o60, "mt:hasCapability", o61)
property(o60, "mt:observes", o62)
property(o51, "mt:hasComponent", o63)
property(o63, "mt:hasCapability", o64)
property(o63, "mt:observes", o65)
property(o2, "mt:hasComponent", o66)
property(o66, "mt:hasCapability", o67)
property(o66, "mt:hasComponent", o68)
property(o68, "mt:hasCapability", o69)
property(o68, "mt:observes", o70)
property(o66, "mt:hasComponent", o71)
property(o71, "mt:hasCapability", o72)
property(o71, "mt:hasComponent", o73)
property(o73, "mt:hasCapability", o74)
property(o73, "mt:observes", o75)
data(o2, "rdfs:label", "Mazak 317641 d1")
data(o2, "mt:hasName", "Mazak")
data(o2, "mt:hasId", "d1")
data(o4, "mt:hasType", "AVAILABILITY")
data(o4, "mt:hasCategory", "EVENT")
data(o4, "mt:hasId", "avail")
data(o5, "mt:hasType", "ASSET_CHANGED")
data(o5, "mt:hasCategory", "EVENT")
data(o5, "mt:hasId", "d1_asset_chg")
data(o6, "mt:hasType", "ASSET_REMOVED")
data(o6, "mt:hasCategory", "EVENT")
data(o6, "mt:hasId", "d1_asset_rem")
data(o7, "rdfs:label", "Mazak 317641 d1 a")
data(o7, "mt:hasName", "base")
data(o7, "mt:hasId", "a")
data(o9, "mt:hasType", "SYSTEM")
data(o9, "mt:hasCategory", "CONDITION")
data(o9, "mt:hasId", "spindle_cond")
data(o10, "rdfs:label", "Mazak 317641 d1 a x")
data(o10, "mt:hasName", "X")
data(o10, "mt:hasId", "x")
data(o12, "mt:hasUnits", "MILLIMETER")
data(o12, "mt:hasType", "POSITION")
data(o12, "mt:hasCategory", "SAMPLE")
data(o12, "mt:hasId", "Xabs")
data(o12, "mt:hasSubType", "ACTUAL")
data(o12, "mt:hasId", "Xpos")
data(o13, "mt:hasType", "POSITION")
data(o13, "mt:hasCategory", "CONDITION")
data(o13, "mt:hasId", "Xtravel")
data(o14, "mt:hasUnits", "CELSIUS")
data(o14, "mt:hasType", "TEMPERATURE")
data(o14, "mt:hasCategory", "SAMPLE")
data(o14, "mt:hasId", "servotemp1")
data(o15, "rdfs:label", "Mazak 317641 d1 a y")
data(o15, "mt:hasName", "Y")
data(o15, "mt:hasId", "y")
data(o17, "mt:hasUnits", "MILLIMETER")
data(o17, "mt:hasType", "POSITION")
data(o17, "mt:hasCategory", "SAMPLE")
data(o17, "mt:hasId", "Yabs")
data(o17, "mt:hasSubType", "ACTUAL")
data(o17, "mt:hasId", "Ypos")
data(o18, "mt:hasType", "POSITION")
data(o18, "mt:hasCategory", "CONDITION")
data(o18, "mt:hasId", "Ytravel")
data(o19, "mt:hasUnits", "CELSIUS")
data(o19, "mt:hasType", "TEMPERATURE")
data(o19, "mt:hasCategory", "SAMPLE")
data(o19, "mt:hasId", "servotemp2")
data(o20, "rdfs:label", "Mazak 317641 d1 a z")
data(o20, "mt:hasName", "Z")
data(o20, "mt:hasId", "z")
data(o22, "mt:hasUnits", "MILLIMETER")
data(o22, "mt:hasType", "POSITION")
data(o22, "mt:hasCategory", "SAMPLE")
data(o22, "mt:hasId", "Zabs")
data(o22, "mt:hasSubType", "ACTUAL")
data(o22, "mt:hasId", "Zpos")
data(o23, "mt:hasType", "POSITION")
data(o23, "mt:hasCategory", "CONDITION")
data(o23, "mt:hasId", "Ztravel")
data(o24, "mt:hasUnits", "CELSIUS")
data(o24, "mt:hasType", "TEMPERATURE")
data(o24, "mt:hasCategory", "SAMPLE")
data(o24, "mt:hasId", "servotemp3")
data(o25, "rdfs:label", "Mazak 317641 d1 a c")
data(o25, "mt:hasName", "C1")
data(o25, "mt:hasId", "c")
data(o27, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o27, "mt:hasType", "ROTARY_VELOCITY")
data(o27, "mt:hasCategory", "SAMPLE")
data(o27, "mt:hasId", "Srpm")
data(o27, "mt:hasSubType", "ACTUAL")
data(o28, "mt:hasUnits", "CELSIUS")
data(o28, "mt:hasType", "TEMPERATURE")
data(o28, "mt:hasCategory", "SAMPLE")
data(o28, "mt:hasId", "Stemp")
data(o29, "mt:hasType", "TEMPERATURE")
data(o29, "mt:hasCategory", "CONDITION")
data(o29, "mt:hasId", "Stemp_cond")
data(o30, "rdfs:label", "Mazak 317641 d1 a br")
data(o30, "mt:hasName", "B")
data(o30, "mt:hasId", "br")
data(o32, "mt:hasType", "ANGLE")
data(o32, "mt:hasCategory", "CONDITION")
data(o32, "mt:hasId", "Btravel")
data(o33, "mt:hasUnits", "DEGREE")
data(o33, "mt:hasType", "ANGLE")
data(o33, "mt:hasCategory", "SAMPLE")
data(o33, "mt:hasId", "Babs")
data(o33, "mt:hasSubType", "ACTUAL")
data(o33, "mt:hasId", "Bpos")
data(o34, "rdfs:label", "Mazak 317641 d1 a c2")
data(o34, "mt:hasName", "C2")
data(o34, "mt:hasId", "c2")
data(o36, "mt:hasType", "ANGLE")
data(o36, "mt:hasCategory", "CONDITION")
data(o36, "mt:hasId", "Ctravel")
data(o37, "mt:hasUnits", "DEGREE")
data(o37, "mt:hasType", "ANGLE")
data(o37, "mt:hasCategory", "SAMPLE")
data(o37, "mt:hasId", "Cabs")
data(o37, "mt:hasSubType", "ACTUAL")
data(o37, "mt:hasId", "Cpos")
data(o38, "mt:hasType", "TEMPERATURE")
data(o38, "mt:hasCategory", "CONDITION")
data(o38, "mt:hasId", "S2temp_cond")
data(o39, "rdfs:label", "Mazak 317641 d1 cont")
data(o39, "mt:hasName", "controller")
data(o39, "mt:hasId", "cont")
data(o41, "mt:hasType", "SYSTEM")
data(o41, "mt:hasCategory", "CONDITION")
data(o41, "mt:hasId", "system_cond")
data(o42, "rdfs:label", "Mazak 317641 d1 cont path1")
data(o42, "mt:hasName", "path")
data(o42, "mt:hasId", "path1")
data(o44, "mt:hasUnits", "MILLIMETER_3D")
data(o44, "mt:hasType", "PATH_POSITION")
data(o44, "mt:hasCategory", "SAMPLE")
data(o44, "mt:hasId", "pathpos")
data(o45, "mt:hasType", "PATH_FEEDRATE_OVERRIDE")
data(o45, "mt:hasCategory", "EVENT")
data(o45, "mt:hasId", "Frapidovr")
data(o45, "mt:hasSubType", "RAPID")
data(o46, "mt:hasType", "PATH_FEEDRATE_OVERRIDE")
data(o46, "mt:hasCategory", "EVENT")
data(o46, "mt:hasId", "Fovr")
data(o46, "mt:hasSubType", "PROGRAMMED")
data(o47, "mt:hasUnits", "MILLIMETER/SECOND")
data(o47, "mt:hasType", "PATH_FEEDRATE")
data(o47, "mt:hasCategory", "SAMPLE")
data(o47, "mt:hasId", "Fact")
data(o47, "mt:hasSubType", "ACTUAL")
data(o48, "mt:hasType", "EXECUTION")
data(o48, "mt:hasCategory", "EVENT")
data(o48, "mt:hasId", "execution")
data(o49, "mt:hasType", "CONTROLLER_MODE")
data(o49, "mt:hasCategory", "EVENT")
data(o49, "mt:hasId", "mode")
data(o50, "mt:hasType", "SYSTEM")
data(o50, "mt:hasCategory", "CONDITION")
data(o50, "mt:hasId", "path_system")
data(o51, "rdfs:label", "Mazak 317641 d1 systems")
data(o51, "mt:hasName", "systems")
data(o51, "mt:hasId", "systems")
data(o53, "rdfs:label", "Mazak 317641 d1 systems hydraulic")
data(o53, "mt:hasName", "hydraulic")
data(o53, "mt:hasId", "hydraulic")
data(o55, "mt:hasType", "SYSTEM")
data(o55, "mt:hasCategory", "CONDITION")
data(o55, "mt:hasId", "hydra_cond")
data(o56, "rdfs:label", "Mazak 317641 d1 systems coolant")
data(o56, "mt:hasName", "coolant")
data(o56, "mt:hasId", "coolant")
data(o58, "mt:hasType", "SYSTEM")
data(o58, "mt:hasCategory", "CONDITION")
data(o58, "mt:hasId", "coolant_cond")
data(o59, "mt:hasUnits", "CELSIUS")
data(o59, "mt:hasType", "TEMPERATURE")
data(o59, "mt:hasCategory", "SAMPLE")
data(o59, "mt:hasId", "cooltemp")
data(o60, "rdfs:label", "Mazak 317641 d1 systems pneumatic")
data(o60, "mt:hasName", "pneumatic")
data(o60, "mt:hasId", "pneumatic")
data(o62, "mt:hasType", "SYSTEM")
data(o62, "mt:hasCategory", "CONDITION")
data(o62, "mt:hasId", "pneu_cond")
data(o63, "rdfs:label", "Mazak 317641 d1 systems lubrication")
data(o63, "mt:hasName", "lubrication")
data(o63, "mt:hasId", "lubrication")
data(o65, "mt:hasType", "SYSTEM")
data(o65, "mt:hasCategory", "CONDITION")
data(o65, "mt:hasId", "lubrication_cond")
data(o66, "rdfs:label", "Mazak 317641 d1 resourcesm")
data(o66, "mt:hasName", "resources")
data(o66, "mt:hasId", "resourcesm")
data(o68, "rdfs:label", "Mazak 317641 d1 resourcesm personnelm")
data(o68, "mt:hasName", "personnel")
data(o68, "mt:hasId", "personnelm")
data(o70, "mt:hasType", "USER")
data(o70, "mt:hasCategory", "EVENT")
data(o70, "mt:hasId", "operator")
data(o71, "rdfs:label", "Mazak 317641 d1 resourcesm materials")
data(o71, "mt:hasName", "materials")
data(o71, "mt:hasId", "materials")
data(o73, "rdfs:label", "Mazak 317641 d1 resourcesm materials procstock")
data(o73, "mt:hasName", "stock")
data(o73, "mt:hasId", "procstock")
data(o75, "mt:hasType", "MATERIAL")
data(o75, "mt:hasCategory", "EVENT")
data(o75, "mt:hasId", "stock")
data(o2, "mt:hasAssetBufferSize", "1024")
data(o2, "mt:hasAssetCount", "67")
@enduml
