
@startuml
' !include https://raw.githubusercontent.com/iofoundry/ontopuml/refs/heads/Development/iof.iuml
!include ../iof.iuml

<style>
object {
  HyperlinkColor #C4E1E6
}
</style>

left to right direction
skinparam linetype polyline
title OKUMAFull

!$default_direction = down

!$namespace_colors = { "bfo":"DFA702", 
                      "iof":"1E90FF", 
                      "ns":"Green", 
                      "ns1":"76608A",
                      "core":"000000",
                      "data":"76608A",
                      "mt":"76608A",
                      "units":"8A2D3B",
                      "cmns-dsg":"3A0519",
                      "qp":"641B2E"
      }
individual(o0, data:ontology2, owl:Ontology)
individual(o1, mt:ontology1, owl:Ontology)
individual(o2, data:OKUMA123456OKUMA.123456, mt:[[../MTConnect.html#Device Device]])
individual(o3, data:OKUMA123456OKUMA.123456Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o4, data:OKUMA123456OKUMA.123456AVAILABILITY, mt:[[../MTConnect.html#AvailabilityDataItem AvailabilityDataItem]])
individual(o5, data:OKUMA123456OKUMA.123456ASSET_CHANGED, mt:[[../MTConnect.html#AssetChangedDataItem AssetChangedDataItem]])
individual(o6, data:OKUMA123456OKUMA.123456ASSET_REMOVED, mt:[[../MTConnect.html#AssetRemovedDataItem AssetRemovedDataItem]])
individual(o7, data:OKUMA123456OKUMA.123456Laxes1, mt:[[../MTConnect.html#Axes Axes]])
individual(o8, data:OKUMA123456OKUMA.123456Laxes1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o9, data:OKUMA123456OKUMA.123456Laxes1Lx1, mt:[[../MTConnect.html#Linear Linear]])
individual(o10, data:OKUMA123456OKUMA.123456Laxes1Lx1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o11, data:OKUMA123456OKUMA.123456Laxes1Lx1POSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o12, data:OKUMA123456OKUMA.123456Laxes1LYI1, mt:[[../MTConnect.html#Linear Linear]])
individual(o13, data:OKUMA123456OKUMA.123456Laxes1LYI1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o14, data:OKUMA123456OKUMA.123456Laxes1LYI1POSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o15, data:OKUMA123456OKUMA.123456Laxes1Lz1, mt:[[../MTConnect.html#Linear Linear]])
individual(o16, data:OKUMA123456OKUMA.123456Laxes1Lz1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o17, data:OKUMA123456OKUMA.123456Laxes1Lz1POSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o18, data:OKUMA123456OKUMA.123456Laxes1Lb1, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o19, data:OKUMA123456OKUMA.123456Laxes1Lb1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o20, data:OKUMA123456OKUMA.123456Laxes1Lb1ANGLE:ACTUAL, mt:[[../MTConnect.html#AngleActualDataItem AngleActualDataItem]])
individual(o21, data:OKUMA123456OKUMA.123456Laxes1Lc1, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o22, data:OKUMA123456OKUMA.123456Laxes1Lc1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o23, data:OKUMA123456OKUMA.123456Laxes1Lc1ROTARY_VELOCITY:ACTUAL, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o24, data:OKUMA123456OKUMA.123456Laxes1Lc1ROTARY_VELOCITY:PROGRAMMED, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o25, data:OKUMA123456OKUMA.123456Laxes1Lz4, mt:[[../MTConnect.html#Linear Linear]])
individual(o26, data:OKUMA123456OKUMA.123456Laxes1Lz4Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o27, data:OKUMA123456OKUMA.123456Laxes1Lz4POSITION:ACTUAL, mt:[[../MTConnect.html#PositionActualDataItem PositionActualDataItem]])
individual(o28, data:OKUMA123456OKUMA.123456Laxes1Lc2, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o29, data:OKUMA123456OKUMA.123456Laxes1Lc2Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o30, data:OKUMA123456OKUMA.123456Laxes1Lc2ROTARY_VELOCITY:ACTUAL, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o31, data:OKUMA123456OKUMA.123456Laxes1Lc2ROTARY_VELOCITY:PROGRAMMED, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o32, data:OKUMA123456OKUMA.123456Laxes1Lc3, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o33, data:OKUMA123456OKUMA.123456Laxes1Lc3Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o34, data:OKUMA123456OKUMA.123456Laxes1Lc3ANGLE:ACTUAL, mt:[[../MTConnect.html#AngleActualDataItem AngleActualDataItem]])
individual(o35, data:OKUMA123456OKUMA.123456Laxes1Lc6, mt:[[../MTConnect.html#Rotary Rotary]])
individual(o36, data:OKUMA123456OKUMA.123456Laxes1Lc6Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o37, data:OKUMA123456OKUMA.123456Laxes1Lc6ROTARY_VELOCITY:ACTUAL, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o38, data:OKUMA123456OKUMA.123456Laxes1Lc6ROTARY_VELOCITY:PROGRAMMED, mt:[[../MTConnect.html#RotaryVelocityDataItem RotaryVelocityDataItem]])
individual(o39, data:OKUMA123456OKUMA.123456Lct1, mt:[[../MTConnect.html#Controller Controller]])
individual(o40, data:OKUMA123456OKUMA.123456Lct1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o41, data:OKUMA123456OKUMA.123456Lct1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o42, data:OKUMA123456OKUMA.123456Lct1CONTROLLER_MODE, mt:[[../MTConnect.html#ControllerModeDataItem ControllerModeDataItem]])
individual(o43, data:OKUMA123456OKUMA.123456Lct1EXECUTION, mt:[[../MTConnect.html#ExecutionDataItem ExecutionDataItem]])
individual(o44, data:OKUMA123456OKUMA.123456Lct1PATH_FEEDRATE_OVERRIDE:PROGRAMMED, mt:[[../MTConnect.html#PathFeedrateOverrideProgrammedDataItem PathFeedrateOverrideProgrammedDataItem]])
individual(o45, data:OKUMA123456OKUMA.123456Lct1Lp1, mt:[[../MTConnect.html#Path Path]])
individual(o46, data:OKUMA123456OKUMA.123456Lct1Lp1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o47, data:OKUMA123456OKUMA.123456Lct1Lp1PATH_FEEDRATE:ACTUAL, mt:[[../MTConnect.html#PathFeedrateActualDataItem PathFeedrateActualDataItem]])
individual(o48, data:OKUMA123456OKUMA.123456Lct1Lp1PATH_FEEDRATE:PROGRAMMED, mt:[[../MTConnect.html#PathFeedrateActualDataItem PathFeedrateActualDataItem]])
individual(o49, data:OKUMA123456OKUMA.123456LSystems1, mt:[[../MTConnect.html#Systems Systems]])
individual(o50, data:OKUMA123456OKUMA.123456LSystems1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o51, data:OKUMA123456OKUMA.123456LSystems1LCoolantSystem1, mt:[[../MTConnect.html#Coolant Coolant]])
individual(o52, data:OKUMA123456OKUMA.123456LSystems1LCoolantSystem1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o53, data:OKUMA123456OKUMA.123456LSystems1LCoolantSystem1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o54, data:OKUMA123456OKUMA.123456LSystems1LHydraulicSystem1, mt:[[../MTConnect.html#Hydraulic Hydraulic]])
individual(o55, data:OKUMA123456OKUMA.123456LSystems1LHydraulicSystem1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o56, data:OKUMA123456OKUMA.123456LSystems1LHydraulicSystem1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o57, data:OKUMA123456OKUMA.123456LSystems1LLubricationSystem1, mt:[[../MTConnect.html#Lubrication Lubrication]])
individual(o58, data:OKUMA123456OKUMA.123456LSystems1LLubricationSystem1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o59, data:OKUMA123456OKUMA.123456LSystems1LLubricationSystem1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o60, data:OKUMA123456OKUMA.123456LSystems1LPneumaticSystem1, mt:[[../MTConnect.html#Pneumatic Pneumatic]])
individual(o61, data:OKUMA123456OKUMA.123456LSystems1LPneumaticSystem1Capability, mt:[[../MTConnect.html#Capability Capability]])
individual(o62, data:OKUMA123456OKUMA.123456LSystems1LPneumaticSystem1SYSTEM_CONDITION, mt:[[../MTConnect.html#SystemConditionDataItem SystemConditionDataItem]])
individual(o63, data:OKUMA123456OKUMA.123456resources, mt:[[../MTConnect.html#Resources Resources]])
individual(o64, data:OKUMA123456OKUMA.123456resourcesCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o65, data:OKUMA123456OKUMA.123456resourcespersonnel, mt:[[../MTConnect.html#Personnel Personnel]])
individual(o66, data:OKUMA123456OKUMA.123456resourcespersonnelCapability, mt:[[../MTConnect.html#Capability Capability]])
individual(o67, data:OKUMA123456OKUMA.123456resourcespersonnelUSER:OPERATOR, mt:[[../MTConnect.html#UserDataItem UserDataItem]])
individual(o68, data:OKUMA123456OKUMA.123456resourcespersonnelUSER:MAINTENANCE, mt:[[../MTConnect.html#UserDataItem UserDataItem]])
individual(o69, data:OKUMA123456OKUMA.123456resourcespersonnelUSER:SET_UP, mt:[[../MTConnect.html#UserDataItem UserDataItem]])
property(o0, "owl:imports", o1)
property(o2, "mt:hasCapability", o3)
property(o2, "mt:observes", o4)
property(o2, "mt:observes", o5)
property(o2, "mt:observes", o6)
property(o2, "mt:hasComponent", o7)
property(o7, "mt:hasCapability", o8)
property(o7, "mt:hasComponent", o9)
property(o9, "mt:hasCapability", o10)
property(o9, "mt:observes", o11)
property(o7, "mt:hasComponent", o12)
property(o12, "mt:hasCapability", o13)
property(o12, "mt:observes", o14)
property(o7, "mt:hasComponent", o15)
property(o15, "mt:hasCapability", o16)
property(o15, "mt:observes", o17)
property(o7, "mt:hasComponent", o18)
property(o18, "mt:hasCapability", o19)
property(o18, "mt:observes", o20)
property(o7, "mt:hasComponent", o21)
property(o21, "mt:hasCapability", o22)
property(o21, "mt:observes", o23)
property(o21, "mt:observes", o24)
property(o7, "mt:hasComponent", o25)
property(o25, "mt:hasCapability", o26)
property(o25, "mt:observes", o27)
property(o7, "mt:hasComponent", o28)
property(o28, "mt:hasCapability", o29)
property(o28, "mt:observes", o30)
property(o28, "mt:observes", o31)
property(o7, "mt:hasComponent", o32)
property(o32, "mt:hasCapability", o33)
property(o32, "mt:observes", o34)
property(o7, "mt:hasComponent", o35)
property(o35, "mt:hasCapability", o36)
property(o35, "mt:observes", o37)
property(o35, "mt:observes", o38)
property(o2, "mt:hasComponent", o39)
property(o39, "mt:hasCapability", o40)
property(o39, "mt:observes", o41)
property(o39, "mt:observes", o42)
property(o39, "mt:observes", o43)
property(o39, "mt:observes", o44)
property(o39, "mt:hasComponent", o45)
property(o45, "mt:hasCapability", o46)
property(o45, "mt:observes", o47)
property(o45, "mt:observes", o48)
property(o2, "mt:hasComponent", o49)
property(o49, "mt:hasCapability", o50)
property(o49, "mt:hasComponent", o51)
property(o51, "mt:hasCapability", o52)
property(o51, "mt:observes", o53)
property(o49, "mt:hasComponent", o54)
property(o54, "mt:hasCapability", o55)
property(o54, "mt:observes", o56)
property(o49, "mt:hasComponent", o57)
property(o57, "mt:hasCapability", o58)
property(o57, "mt:observes", o59)
property(o49, "mt:hasComponent", o60)
property(o60, "mt:hasCapability", o61)
property(o60, "mt:observes", o62)
property(o2, "mt:hasComponent", o63)
property(o63, "mt:hasCapability", o64)
property(o63, "mt:hasComponent", o65)
property(o65, "mt:hasCapability", o66)
property(o65, "mt:observes", o67)
property(o65, "mt:observes", o68)
property(o65, "mt:observes", o69)
data(o2, "rdfs:label", "OKUMA 123456 OKUMA.123456")
data(o2, "mt:hasName", "OKUMA")
data(o2, "mt:hasId", "OKUMA.123456")
data(o4, "mt:hasType", "AVAILABILITY")
data(o4, "mt:hasCategory", "EVENT")
data(o4, "mt:hasId", "Lavail")
data(o4, "mt:hasName", "avail")
data(o5, "mt:hasType", "ASSET_CHANGED")
data(o5, "mt:hasCategory", "EVENT")
data(o5, "mt:hasId", "OKUMA.123456_asset_chg")
data(o6, "mt:hasType", "ASSET_REMOVED")
data(o6, "mt:hasCategory", "EVENT")
data(o6, "mt:hasId", "OKUMA.123456_asset_rem")
data(o7, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1")
data(o7, "mt:hasName", "Axes")
data(o7, "mt:hasId", "Laxes1")
data(o9, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lx1")
data(o9, "mt:hasName", "X")
data(o9, "mt:hasId", "Lx1")
data(o11, "mt:hasUnits", "MILLIMETER")
data(o11, "mt:hasType", "POSITION")
data(o11, "mt:hasCategory", "SAMPLE")
data(o11, "mt:hasId", "LX1actm")
data(o11, "mt:hasName", "X1actm")
data(o11, "mt:hasSubType", "ACTUAL")
data(o11, "mt:hasId", "LX1actw")
data(o11, "mt:hasName", "X1actw")
data(o12, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 LYI1")
data(o12, "mt:hasName", "Y")
data(o12, "mt:hasId", "LYI1")
data(o14, "mt:hasUnits", "MILLIMETER")
data(o14, "mt:hasType", "POSITION")
data(o14, "mt:hasCategory", "SAMPLE")
data(o14, "mt:hasId", "LYI1actm")
data(o14, "mt:hasName", "YI1actm")
data(o14, "mt:hasSubType", "ACTUAL")
data(o14, "mt:hasId", "LYI1actw")
data(o14, "mt:hasName", "YI1actw")
data(o15, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lz1")
data(o15, "mt:hasName", "Z1")
data(o15, "mt:hasId", "Lz1")
data(o17, "mt:hasUnits", "MILLIMETER")
data(o17, "mt:hasType", "POSITION")
data(o17, "mt:hasCategory", "SAMPLE")
data(o17, "mt:hasId", "LZ1actm")
data(o17, "mt:hasName", "Z1actm")
data(o17, "mt:hasSubType", "ACTUAL")
data(o17, "mt:hasId", "LZ1actw")
data(o17, "mt:hasName", "Z1actw")
data(o18, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lb1")
data(o18, "mt:hasName", "B")
data(o18, "mt:hasId", "Lb1")
data(o20, "mt:hasUnits", "DEGREE")
data(o20, "mt:hasType", "ANGLE")
data(o20, "mt:hasCategory", "SAMPLE")
data(o20, "mt:hasId", "LB1actw")
data(o20, "mt:hasName", "B1actw")
data(o20, "mt:hasSubType", "ACTUAL")
data(o21, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lc1")
data(o21, "mt:hasName", "C1")
data(o21, "mt:hasId", "Lc1")
data(o23, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o23, "mt:hasType", "ROTARY_VELOCITY")
data(o23, "mt:hasCategory", "SAMPLE")
data(o23, "mt:hasId", "LS1speed")
data(o23, "mt:hasName", "S1speed")
data(o23, "mt:hasSubType", "ACTUAL")
data(o24, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o24, "mt:hasType", "ROTARY_VELOCITY")
data(o24, "mt:hasCategory", "SAMPLE")
data(o24, "mt:hasId", "LS1cmd")
data(o24, "mt:hasName", "S1cmd")
data(o24, "mt:hasSubType", "PROGRAMMED")
data(o25, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lz4")
data(o25, "mt:hasName", "Z4")
data(o25, "mt:hasId", "Lz4")
data(o27, "mt:hasUnits", "MILLIMETER")
data(o27, "mt:hasType", "POSITION")
data(o27, "mt:hasCategory", "SAMPLE")
data(o27, "mt:hasId", "LZ4actm")
data(o27, "mt:hasName", "Z4actm")
data(o27, "mt:hasSubType", "ACTUAL")
data(o27, "mt:hasId", "LZ4actw")
data(o27, "mt:hasName", "Z4actw")
data(o28, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lc2")
data(o28, "mt:hasName", "C2")
data(o28, "mt:hasId", "Lc2")
data(o30, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o30, "mt:hasType", "ROTARY_VELOCITY")
data(o30, "mt:hasCategory", "SAMPLE")
data(o30, "mt:hasId", "LS2speed")
data(o30, "mt:hasName", "S2speed")
data(o30, "mt:hasSubType", "ACTUAL")
data(o31, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o31, "mt:hasType", "ROTARY_VELOCITY")
data(o31, "mt:hasCategory", "SAMPLE")
data(o31, "mt:hasId", "LS2cmd")
data(o31, "mt:hasName", "S2cmd")
data(o31, "mt:hasSubType", "PROGRAMMED")
data(o32, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lc3")
data(o32, "mt:hasName", "C3")
data(o32, "mt:hasId", "Lc3")
data(o34, "mt:hasUnits", "DEGREE")
data(o34, "mt:hasType", "ANGLE")
data(o34, "mt:hasCategory", "SAMPLE")
data(o34, "mt:hasId", "LC3actm")
data(o34, "mt:hasName", "C3actm")
data(o34, "mt:hasSubType", "ACTUAL")
data(o34, "mt:hasId", "LC3actw")
data(o34, "mt:hasName", "C3actw")
data(o35, "rdfs:label", "OKUMA 123456 OKUMA.123456 Laxes1 Lc6")
data(o35, "mt:hasName", "C6")
data(o35, "mt:hasId", "Lc6")
data(o37, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o37, "mt:hasType", "ROTARY_VELOCITY")
data(o37, "mt:hasCategory", "SAMPLE")
data(o37, "mt:hasId", "LS6speed")
data(o37, "mt:hasName", "S6speed")
data(o37, "mt:hasSubType", "ACTUAL")
data(o38, "mt:hasUnits", "REVOLUTION/MINUTE")
data(o38, "mt:hasType", "ROTARY_VELOCITY")
data(o38, "mt:hasCategory", "SAMPLE")
data(o38, "mt:hasId", "LS6cmd")
data(o38, "mt:hasName", "S6cmd")
data(o38, "mt:hasSubType", "PROGRAMMED")
data(o39, "rdfs:label", "OKUMA 123456 OKUMA.123456 Lct1")
data(o39, "mt:hasName", "Controller")
data(o39, "mt:hasId", "Lct1")
data(o41, "mt:hasType", "SYSTEM")
data(o41, "mt:hasCategory", "CONDITION")
data(o41, "mt:hasId", "Lsystem")
data(o41, "mt:hasName", "system")
data(o42, "mt:hasType", "CONTROLLER_MODE")
data(o42, "mt:hasCategory", "EVENT")
data(o42, "mt:hasId", "Lpmode")
data(o42, "mt:hasName", "pmode")
data(o43, "mt:hasType", "EXECUTION")
data(o43, "mt:hasCategory", "EVENT")
data(o43, "mt:hasId", "Lpexecution")
data(o43, "mt:hasName", "pexecution")
data(o44, "mt:hasUnits", "PERCENT")
data(o44, "mt:hasType", "PATH_FEEDRATE_OVERRIDE")
data(o44, "mt:hasCategory", "EVENT")
data(o44, "mt:hasId", "LpFovr")
data(o44, "mt:hasName", "pFovr")
data(o44, "mt:hasSubType", "PROGRAMMED")
data(o45, "rdfs:label", "OKUMA 123456 OKUMA.123456 Lct1 Lp1")
data(o45, "mt:hasName", "path")
data(o45, "mt:hasId", "Lp1")
data(o47, "mt:hasUnits", "MILLIMETER/SECOND")
data(o47, "mt:hasType", "PATH_FEEDRATE")
data(o47, "mt:hasCategory", "SAMPLE")
data(o47, "mt:hasId", "Lp1Fact")
data(o47, "mt:hasName", "p1Fact")
data(o47, "mt:hasSubType", "ACTUAL")
data(o48, "mt:hasUnits", "MILLIMETER/SECOND")
data(o48, "mt:hasType", "PATH_FEEDRATE")
data(o48, "mt:hasCategory", "SAMPLE")
data(o48, "mt:hasId", "Lp1Fcmd")
data(o48, "mt:hasName", "p1Fcmd")
data(o48, "mt:hasSubType", "PROGRAMMED")
data(o49, "rdfs:label", "OKUMA 123456 OKUMA.123456 LSystems1")
data(o49, "mt:hasName", "Systems1")
data(o49, "mt:hasId", "LSystems1")
data(o51, "rdfs:label", "OKUMA 123456 OKUMA.123456 LSystems1 LCoolantSystem1")
data(o51, "mt:hasName", "CoolantSystem1")
data(o51, "mt:hasId", "LCoolantSystem1")
data(o53, "mt:hasType", "SYSTEM")
data(o53, "mt:hasCategory", "CONDITION")
data(o53, "mt:hasId", "LCoolantSystem1_cond")
data(o53, "mt:hasName", "CoolantSystem1_cond")
data(o54, "rdfs:label", "OKUMA 123456 OKUMA.123456 LSystems1 LHydraulicSystem1")
data(o54, "mt:hasName", "HydraulicSystem1")
data(o54, "mt:hasId", "LHydraulicSystem1")
data(o56, "mt:hasType", "SYSTEM")
data(o56, "mt:hasCategory", "CONDITION")
data(o56, "mt:hasId", "LHydraulicSystem1_cond")
data(o56, "mt:hasName", "HydraulicSystem1_cond")
data(o57, "rdfs:label", "OKUMA 123456 OKUMA.123456 LSystems1 LLubricationSystem1")
data(o57, "mt:hasName", "LubricationSystem1")
data(o57, "mt:hasId", "LLubricationSystem1")
data(o59, "mt:hasType", "SYSTEM")
data(o59, "mt:hasCategory", "CONDITION")
data(o59, "mt:hasId", "LLubricationSystem_cond")
data(o59, "mt:hasName", "LubricationSystem1_cond")
data(o60, "rdfs:label", "OKUMA 123456 OKUMA.123456 LSystems1 LPneumaticSystem1")
data(o60, "mt:hasName", "PneumaticSystem1")
data(o60, "mt:hasId", "LPneumaticSystem1")
data(o62, "mt:hasType", "SYSTEM")
data(o62, "mt:hasCategory", "CONDITION")
data(o62, "mt:hasId", "LPneumaticSystem1_cond")
data(o62, "mt:hasName", "PneumaticSystem1_cond")
data(o63, "rdfs:label", "OKUMA 123456 OKUMA.123456 resources")
data(o63, "mt:hasName", "resources")
data(o63, "mt:hasId", "resources")
data(o65, "rdfs:label", "OKUMA 123456 OKUMA.123456 resources personnel")
data(o65, "mt:hasName", "personnel")
data(o65, "mt:hasId", "personnel")
data(o67, "mt:hasType", "USER")
data(o67, "mt:hasCategory", "EVENT")
data(o67, "mt:hasId", "MachineOperator")
data(o67, "mt:hasName", "MachineOperator")
data(o67, "mt:hasSubType", "OPERATOR")
data(o68, "mt:hasType", "USER")
data(o68, "mt:hasCategory", "EVENT")
data(o68, "mt:hasId", "MachineMaintenance")
data(o68, "mt:hasName", "MachineMaintenance")
data(o68, "mt:hasSubType", "MAINTENANCE")
data(o69, "mt:hasType", "USER")
data(o69, "mt:hasCategory", "EVENT")
data(o69, "mt:hasId", "MachineSetup")
data(o69, "mt:hasName", "MachineSetup")
data(o69, "mt:hasSubType", "SET_UP")
data(o2, "mt:hasAssetBufferSize", "1024")
data(o2, "mt:hasAssetCount", "67")
@enduml
